[package]
name = "ch4-sat-mailbox"
version = "0.1.0"
authors = ["John Gillott <jsgtwenty@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
